# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  host: 0.0.0.0
  # 程序监听端口
  port: 10000
  ws-port: 10000
  # rsa公钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-public-key: rsa-pub.pem
  # rsa私钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-private-key: rsa-priv.pem
  # web路径
  http-base-web: http://localhost:8080/

file:
  # 文件根路径,如果为空，则默认以项目所在目录
  store-base-path: /Users/lishoujie/files/
  # 文件上传最大限制
  allow-max-size: 1024
  # 允许可以上传的文件后缀名，如jpg,jpeg,png等。留空允许所有。
  allow-extensions:
  # 是否自动重命名,默认不自动重命名,使用原文件名
  rename-file: false
  # 下载是否需带token,真假
  download-use-token: false
  # 下载token过期时间": "单位秒"
  download-token-expire: 600
  #文件去重算法md5可能存在冲突，默认md5: "sha1|md5",
  file-sum-arithmetic: md5
  # 文件是否去重": "默认去重",
  enable-distinct-file: true

# jwt配置
jwt:
  # jwt标识
  realm: share-ac-cn
  # 服务端密钥
  key: SHARE-N7Ak8hgzOySANmkD2C2OR11jhRW8dpBGTJSgUsE
  # token过期时间, 小时
  timeout: 12
  # 刷新token最大过期时间, 小时
  max-refresh: 12

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

mysql:
  # 用户名
  username: root
  # 密码
  password: root
  # 数据库名
  database: db_sz_clock
  # 主机地址
  host: localhost
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci
redis:
  address: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  size: 30
  conn-max: 30

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200
